package soap.com.epam.lab.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.ws.rs.core.Response;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "LetterService", targetNamespace = "http://soap.services.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
//@XmlSeeAlso({ObjectFactory.class})
public interface MailClient {
         /**
         *
         * @param subject
         * @return
         *     returns rest.lab.epam.services.soap.Response
         */
        @WebMethod
        @WebResult(partName = "return")
        public Response getLetterBySubject(
                @WebParam(name = "subject", partName = "subject")
                        String subject);
        /**
         *
         * @param subject
         * @param mailTo
         * @param body
         * @return
         *     returns rest.lab.epam.services.soap.Response
         */
        @WebMethod
        @WebResult(partName = "return")
        public Response sendLetter(
                @WebParam(name = "subject", partName = "subject")
                        String subject,
                @WebParam(name = "mailTo", partName = "mailTo")
                        String mailTo,
                @WebParam(name = "body", partName = "body")
                        String body);
        /**
         *
         * @param subject
         * @param mailTo
         * @param body
         * @return
         *     returns rest.lab.epam.services.soap.Response
         */
        @WebMethod
        @WebResult(partName = "return")
        public Response removeLetter(
                @WebParam(name = "subject", partName = "subject")
                        String subject,
                @WebParam(name = "mailTo", partName = "mailTo")
                        String mailTo,
                @WebParam(name = "body", partName = "body")
                        String body);
        /**
         *
         * @return
         *     returns rest.lab.epam.services.soap.Response
         */
        @WebMethod
        @WebResult(partName = "return")
        public Response getAll();

        /**
         *
         * @param email
         * @return
         *     returns rest.lab.epam.services.soap.Response
         */
        @WebMethod
        @WebResult(partName = "return")
        public Response getLetterByEmail(
                @WebParam(name = "email", partName = "email")
                        String email);
}
